"""Constants for Climate Manager."""
from __future__ import annotations

from datetime import timedelta
from typing import Final

DOMAIN: Final = "climate_manager"
PLATFORMS: Final = ["sensor", "binary_sensor", "button", "switch"]

DATA_MANAGER: Final = "manager"
SERVICE_RECALCULATE: Final = "recalculate"
SERVICE_CLEAR_OVERRIDE: Final = "clear_override"
SERVICE_PAUSE: Final = "pause"
SERVICE_RESUME: Final = "resume"
SERVICE_SET_TEMPORARY_OVERRIDE: Final = "set_temporary_override"

STORAGE_VERSION: Final = 1
STORAGE_KEY: Final = f"{DOMAIN}_runtime"

PROFILE_HOME: Final = "home"
PROFILE_SLEEP: Final = "sleep"
PROFILE_AWAY: Final = "away"
PROFILE_GUEST: Final = "guest"
PROFILE_SENSORS_OPEN: Final = "sensors_open"
PROFILE_MANUAL_OVERRIDE: Final = "manual_override"
PROFILE_PAUSED: Final = "paused"
PROFILE_OVERRIDE_LOCK: Final = "override_lock"

PROFILES: Final = [
    PROFILE_HOME,
    PROFILE_SLEEP,
    PROFILE_AWAY,
    PROFILE_GUEST,
    PROFILE_SENSORS_OPEN,
    PROFILE_MANUAL_OVERRIDE,
    PROFILE_PAUSED,
    PROFILE_OVERRIDE_LOCK,
]

HVAC_PREF_AUTO: Final = "auto"
HVAC_PREF_HEAT: Final = "heat"
HVAC_PREF_COOL: Final = "cool"
HVAC_PREF_OFF: Final = "off"
HVAC_PREFERENCES: Final = [HVAC_PREF_AUTO, HVAC_PREF_HEAT, HVAC_PREF_COOL, HVAC_PREF_OFF]

MANUAL_BEHAVIOR_IGNORE: Final = "ignore"
MANUAL_BEHAVIOR_TEMPORARY: Final = "temporary_override"
MANUAL_BEHAVIOR_HOLD: Final = "hold_until_cleared"
MANUAL_BEHAVIORS: Final = [
    MANUAL_BEHAVIOR_IGNORE,
    MANUAL_BEHAVIOR_TEMPORARY,
    MANUAL_BEHAVIOR_HOLD,
]

WINDOWS_ACTION_OFF: Final = "off"
WINDOWS_ACTION_HEAT_SETBACK: Final = "heat_setback"
WINDOWS_ACTION_COOL_SETBACK: Final = "cool_setback"
WINDOWS_ACTIONS: Final = [
    WINDOWS_ACTION_OFF,
    WINDOWS_ACTION_HEAT_SETBACK,
    WINDOWS_ACTION_COOL_SETBACK,
]

STATUS_CONTROLLING: Final = "controlling"
STATUS_PAUSED: Final = "paused"
STATUS_MANUAL_OVERRIDE: Final = "manual_override"
STATUS_WINDOWS_BACKOFF: Final = "windows_backoff"
STATUS_UNAVAILABLE: Final = "unavailable"
STATUS_IDLE: Final = "idle"

CONF_THERMOSTAT_ENTITY = "thermostat_entity"
CONF_OUTDOOR_TEMP_ENTITY = "outdoor_temp_entity"
CONF_SLEEP_SCHEDULE_ENTITY = "sleep_schedule_entity"
CONF_AWAY_ENTITY = "away_entity"
CONF_GUEST_ENTITY = "guest_entity"
CONF_OVERRIDE_ENTITY = "override_entity"
CONF_WINDOWS_ENTITY = "windows_entity"
CONF_SEASON_ENTITY = "season_entity"
CONF_SMART_CONTROL_ENABLED = "smart_control_enabled"
CONF_HVAC_PREFERENCE = "hvac_preference"
CONF_HEAT_HOME = "heat_home"
CONF_HEAT_SLEEP = "heat_sleep"
CONF_HEAT_GUEST = "heat_guest"
CONF_HEAT_AWAY = "heat_away"
CONF_COOL_HOME = "cool_home"
CONF_COOL_SLEEP = "cool_sleep"
CONF_COOL_GUEST = "cool_guest"
CONF_COOL_AWAY = "cool_away"
CONF_CURVE_BAND_1_MAX = "curve_band_1_max"
CONF_CURVE_BAND_1_OFFSET = "curve_band_1_offset"
CONF_CURVE_BAND_2_MAX = "curve_band_2_max"
CONF_CURVE_BAND_2_OFFSET = "curve_band_2_offset"
CONF_CURVE_BAND_3_MAX = "curve_band_3_max"
CONF_CURVE_BAND_3_OFFSET = "curve_band_3_offset"
CONF_CURVE_BAND_4_MAX = "curve_band_4_max"
CONF_CURVE_BAND_4_OFFSET = "curve_band_4_offset"
CONF_CURVE_WEIGHT_HOME = "curve_weight_home"
CONF_CURVE_WEIGHT_SLEEP = "curve_weight_sleep"
CONF_CURVE_WEIGHT_GUEST = "curve_weight_guest"
CONF_CURVE_WEIGHT_AWAY = "curve_weight_away"
CONF_COOL_CURVE_BAND_1_MIN = "cool_curve_band_1_min"
CONF_COOL_CURVE_BAND_1_OFFSET = "cool_curve_band_1_offset"
CONF_COOL_CURVE_BAND_2_MIN = "cool_curve_band_2_min"
CONF_COOL_CURVE_BAND_2_OFFSET = "cool_curve_band_2_offset"
CONF_COOL_CURVE_BAND_3_MIN = "cool_curve_band_3_min"
CONF_COOL_CURVE_BAND_3_OFFSET = "cool_curve_band_3_offset"
CONF_COOL_CURVE_BAND_4_MIN = "cool_curve_band_4_min"
CONF_COOL_CURVE_BAND_4_OFFSET = "cool_curve_band_4_offset"
CONF_COOL_CURVE_WEIGHT_HOME = "cool_curve_weight_home"
CONF_COOL_CURVE_WEIGHT_SLEEP = "cool_curve_weight_sleep"
CONF_COOL_CURVE_WEIGHT_GUEST = "cool_curve_weight_guest"
CONF_COOL_CURVE_WEIGHT_AWAY = "cool_curve_weight_away"
CONF_MANUAL_TEMP_BEHAVIOR = "manual_temp_behavior"
CONF_MANUAL_MODE_BEHAVIOR = "manual_mode_behavior"
CONF_OVERRIDE_DURATION_MINUTES = "override_duration_minutes"
CONF_MANUAL_GRACE_SECONDS = "manual_grace_seconds"
CONF_WINDOWS_OPEN_DELAY_MINUTES = "windows_open_delay_minutes"
CONF_WINDOWS_RESTORE_DELAY_MINUTES = "windows_restore_delay_minutes"
CONF_WINDOWS_ACTION = "windows_action"
CONF_MIN_HEAT_TARGET = "min_heat_target"
CONF_MAX_HEAT_TARGET = "max_heat_target"
CONF_MIN_COOL_TARGET = "min_cool_target"
CONF_MAX_COOL_TARGET = "max_cool_target"
CONF_TEMP_CHANGE_THRESHOLD = "temp_change_threshold"
CONF_CANCEL_OVERRIDE_ON_AWAY = "cancel_override_on_away"
CONF_CANCEL_OVERRIDE_ON_WINDOWS = "cancel_override_on_windows"
CONF_CANCEL_OVERRIDE_ON_SLEEP = "cancel_override_on_sleep"
CONF_DEBUG_MANUAL_DETECTION = "debug_manual_detection"

DEFAULT_HEAT_HOME = 69.0
DEFAULT_HEAT_SLEEP = 67.0
DEFAULT_HEAT_GUEST = 70.0
DEFAULT_HEAT_AWAY = 62.0
DEFAULT_COOL_HOME = 73.0
DEFAULT_COOL_SLEEP = 72.0
DEFAULT_COOL_GUEST = 73.0
DEFAULT_COOL_AWAY = 78.0
DEFAULT_CURVE_BAND_1_MAX = 35.0
DEFAULT_CURVE_BAND_1_OFFSET = 3.0
DEFAULT_CURVE_BAND_2_MAX = 45.0
DEFAULT_CURVE_BAND_2_OFFSET = 2.0
DEFAULT_CURVE_BAND_3_MAX = 55.0
DEFAULT_CURVE_BAND_3_OFFSET = 1.5
DEFAULT_CURVE_BAND_4_MAX = 62.0
DEFAULT_CURVE_BAND_4_OFFSET = 0.5
DEFAULT_CURVE_WEIGHT_HOME = 1.0
DEFAULT_CURVE_WEIGHT_SLEEP = 0.5
DEFAULT_CURVE_WEIGHT_GUEST = 1.0
DEFAULT_CURVE_WEIGHT_AWAY = 0.0
DEFAULT_COOL_CURVE_BAND_1_MIN = 75.0
DEFAULT_COOL_CURVE_BAND_1_OFFSET = -0.5
DEFAULT_COOL_CURVE_BAND_2_MIN = 85.0
DEFAULT_COOL_CURVE_BAND_2_OFFSET = -1.5
DEFAULT_COOL_CURVE_BAND_3_MIN = 95.0
DEFAULT_COOL_CURVE_BAND_3_OFFSET = -2.0
DEFAULT_COOL_CURVE_BAND_4_MIN = 105.0
DEFAULT_COOL_CURVE_BAND_4_OFFSET = -3.0
DEFAULT_COOL_CURVE_WEIGHT_HOME = 1.0
DEFAULT_COOL_CURVE_WEIGHT_SLEEP = 0.5
DEFAULT_COOL_CURVE_WEIGHT_GUEST = 1.0
DEFAULT_COOL_CURVE_WEIGHT_AWAY = 0.0
DEFAULT_OVERRIDE_DURATION_MINUTES = 120
DEFAULT_MANUAL_GRACE_SECONDS = 20
DEFAULT_WINDOWS_OPEN_DELAY_MINUTES = 15
DEFAULT_WINDOWS_RESTORE_DELAY_MINUTES = 15
DEFAULT_WINDOWS_ACTION = WINDOWS_ACTION_OFF
DEFAULT_SMART_CONTROL_ENABLED = True
DEFAULT_HVAC_PREFERENCE = HVAC_PREF_AUTO
WINDOWS_FREEZE_PROTECTION_OUTDOOR_TEMP = 50.0
WINDOWS_FREEZE_PROTECTION_HEAT_TARGET = 50.0
DEFAULT_MIN_HEAT_TARGET = 60.0
DEFAULT_MAX_HEAT_TARGET = 75.0
DEFAULT_MIN_COOL_TARGET = 68.0
DEFAULT_MAX_COOL_TARGET = 82.0
DEFAULT_TEMP_CHANGE_THRESHOLD = 0.5
DEFAULT_CANCEL_OVERRIDE_ON_AWAY = True
DEFAULT_CANCEL_OVERRIDE_ON_WINDOWS = True
DEFAULT_CANCEL_OVERRIDE_ON_SLEEP = False
DEFAULT_DEBUG_MANUAL_DETECTION = False

DEFAULT_OPTIONS: Final = {
    CONF_SMART_CONTROL_ENABLED: DEFAULT_SMART_CONTROL_ENABLED,
    CONF_HVAC_PREFERENCE: DEFAULT_HVAC_PREFERENCE,
    CONF_HEAT_HOME: DEFAULT_HEAT_HOME,
    CONF_HEAT_SLEEP: DEFAULT_HEAT_SLEEP,
    CONF_HEAT_GUEST: DEFAULT_HEAT_GUEST,
    CONF_HEAT_AWAY: DEFAULT_HEAT_AWAY,
    CONF_COOL_HOME: DEFAULT_COOL_HOME,
    CONF_COOL_SLEEP: DEFAULT_COOL_SLEEP,
    CONF_COOL_GUEST: DEFAULT_COOL_GUEST,
    CONF_COOL_AWAY: DEFAULT_COOL_AWAY,
    CONF_CURVE_BAND_1_MAX: DEFAULT_CURVE_BAND_1_MAX,
    CONF_CURVE_BAND_1_OFFSET: DEFAULT_CURVE_BAND_1_OFFSET,
    CONF_CURVE_BAND_2_MAX: DEFAULT_CURVE_BAND_2_MAX,
    CONF_CURVE_BAND_2_OFFSET: DEFAULT_CURVE_BAND_2_OFFSET,
    CONF_CURVE_BAND_3_MAX: DEFAULT_CURVE_BAND_3_MAX,
    CONF_CURVE_BAND_3_OFFSET: DEFAULT_CURVE_BAND_3_OFFSET,
    CONF_CURVE_BAND_4_MAX: DEFAULT_CURVE_BAND_4_MAX,
    CONF_CURVE_BAND_4_OFFSET: DEFAULT_CURVE_BAND_4_OFFSET,
    CONF_CURVE_WEIGHT_HOME: DEFAULT_CURVE_WEIGHT_HOME,
    CONF_CURVE_WEIGHT_SLEEP: DEFAULT_CURVE_WEIGHT_SLEEP,
    CONF_CURVE_WEIGHT_GUEST: DEFAULT_CURVE_WEIGHT_GUEST,
    CONF_CURVE_WEIGHT_AWAY: DEFAULT_CURVE_WEIGHT_AWAY,
    CONF_COOL_CURVE_BAND_1_MIN: DEFAULT_COOL_CURVE_BAND_1_MIN,
    CONF_COOL_CURVE_BAND_1_OFFSET: DEFAULT_COOL_CURVE_BAND_1_OFFSET,
    CONF_COOL_CURVE_BAND_2_MIN: DEFAULT_COOL_CURVE_BAND_2_MIN,
    CONF_COOL_CURVE_BAND_2_OFFSET: DEFAULT_COOL_CURVE_BAND_2_OFFSET,
    CONF_COOL_CURVE_BAND_3_MIN: DEFAULT_COOL_CURVE_BAND_3_MIN,
    CONF_COOL_CURVE_BAND_3_OFFSET: DEFAULT_COOL_CURVE_BAND_3_OFFSET,
    CONF_COOL_CURVE_BAND_4_MIN: DEFAULT_COOL_CURVE_BAND_4_MIN,
    CONF_COOL_CURVE_BAND_4_OFFSET: DEFAULT_COOL_CURVE_BAND_4_OFFSET,
    CONF_COOL_CURVE_WEIGHT_HOME: DEFAULT_COOL_CURVE_WEIGHT_HOME,
    CONF_COOL_CURVE_WEIGHT_SLEEP: DEFAULT_COOL_CURVE_WEIGHT_SLEEP,
    CONF_COOL_CURVE_WEIGHT_GUEST: DEFAULT_COOL_CURVE_WEIGHT_GUEST,
    CONF_COOL_CURVE_WEIGHT_AWAY: DEFAULT_COOL_CURVE_WEIGHT_AWAY,
    CONF_MANUAL_TEMP_BEHAVIOR: MANUAL_BEHAVIOR_TEMPORARY,
    CONF_MANUAL_MODE_BEHAVIOR: MANUAL_BEHAVIOR_TEMPORARY,
    CONF_OVERRIDE_DURATION_MINUTES: DEFAULT_OVERRIDE_DURATION_MINUTES,
    CONF_MANUAL_GRACE_SECONDS: DEFAULT_MANUAL_GRACE_SECONDS,
    CONF_WINDOWS_OPEN_DELAY_MINUTES: DEFAULT_WINDOWS_OPEN_DELAY_MINUTES,
    CONF_WINDOWS_RESTORE_DELAY_MINUTES: DEFAULT_WINDOWS_RESTORE_DELAY_MINUTES,
    CONF_WINDOWS_ACTION: DEFAULT_WINDOWS_ACTION,
    CONF_MIN_HEAT_TARGET: DEFAULT_MIN_HEAT_TARGET,
    CONF_MAX_HEAT_TARGET: DEFAULT_MAX_HEAT_TARGET,
    CONF_MIN_COOL_TARGET: DEFAULT_MIN_COOL_TARGET,
    CONF_MAX_COOL_TARGET: DEFAULT_MAX_COOL_TARGET,
    CONF_TEMP_CHANGE_THRESHOLD: DEFAULT_TEMP_CHANGE_THRESHOLD,
    CONF_CANCEL_OVERRIDE_ON_AWAY: DEFAULT_CANCEL_OVERRIDE_ON_AWAY,
    CONF_CANCEL_OVERRIDE_ON_WINDOWS: DEFAULT_CANCEL_OVERRIDE_ON_WINDOWS,
    CONF_CANCEL_OVERRIDE_ON_SLEEP: DEFAULT_CANCEL_OVERRIDE_ON_SLEEP,
    CONF_DEBUG_MANUAL_DETECTION: DEFAULT_DEBUG_MANUAL_DETECTION,
}

RUNTIME_SAVE_DEBOUNCE = timedelta(seconds=2)
